#!/bin/bash

cp 1941.rom /media/$USER/POCKET/Assets/jtcps1/common
cp 1941j.rom /media/$USER/POCKET/Assets/jtcps1/common
cp 1941r1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp 1941u.rom /media/$USER/POCKET/Assets/jtcps1/common
cp 3wonders.rom /media/$USER/POCKET/Assets/jtcps1/common
cp 3wondrsb.rom /media/$USER/POCKET/Assets/jtcps1/common
cp 3wondrsh.rom /media/$USER/POCKET/Assets/jtcps1/common
cp 3wondsr1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp 3wondrsu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp area88.rom /media/$USER/POCKET/Assets/jtcps1/common
cp area88r.rom /media/$USER/POCKET/Assets/jtcps1/common
cp captcomm.rom /media/$USER/POCKET/Assets/jtcps1/common
cp captcmmb.rom /media/$USER/POCKET/Assets/jtcps1/common
cp captcmmj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp captcjr1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp captcmr1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp captcmmu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp cawing.rom /media/$USER/POCKET/Assets/jtcps1/common
cp cawingj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp cawingr1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp cawingu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp cawinur1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp chikij.rom /media/$USER/POCKET/Assets/jtcps1/common
cp cworld2j.rom /media/$USER/POCKET/Assets/jtcps1/common
cp cworl2ja.rom /media/$USER/POCKET/Assets/jtcps1/common
cp cworl2jb.rom /media/$USER/POCKET/Assets/jtcps1/common
cp daimakai.rom /media/$USER/POCKET/Assets/jtcps1/common
cp daimaair.rom /media/$USER/POCKET/Assets/jtcps1/common
cp dynwar.rom /media/$USER/POCKET/Assets/jtcps1/common
cp dynwara.rom /media/$USER/POCKET/Assets/jtcps1/common
cp dynwarj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp dynwarjr.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffight.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffighta.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffightj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffightj1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffightj2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffightj3.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffightj4.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffightjh.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffightu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffightu1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffightua.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffightub.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ffightuc.rom /media/$USER/POCKET/Assets/jtcps1/common
cp forgottn.rom /media/$USER/POCKET/Assets/jtcps1/common
cp forgotna.rom /media/$USER/POCKET/Assets/jtcps1/common
cp forgotnu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp forgonua.rom /media/$USER/POCKET/Assets/jtcps1/common
cp forgouaa.rom /media/$USER/POCKET/Assets/jtcps1/common
cp forgonuc.rom /media/$USER/POCKET/Assets/jtcps1/common
cp forgonue.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ganbare.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ghouls.rom /media/$USER/POCKET/Assets/jtcps1/common
cp ghoulsu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp gulunpa.rom /media/$USER/POCKET/Assets/jtcps1/common
cp knights.rom /media/$USER/POCKET/Assets/jtcps1/common
cp knighsb2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp knightsj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp knighsja.rom /media/$USER/POCKET/Assets/jtcps1/common
cp knightsu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp kod.rom /media/$USER/POCKET/Assets/jtcps1/common
cp kodj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp kodja.rom /media/$USER/POCKET/Assets/jtcps1/common
cp kodr1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp kodr2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp kodu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp lostwrld.rom /media/$USER/POCKET/Assets/jtcps1/common
cp lostwldo.rom /media/$USER/POCKET/Assets/jtcps1/common
cp mbomberj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp megaman.rom /media/$USER/POCKET/Assets/jtcps1/common
cp megamana.rom /media/$USER/POCKET/Assets/jtcps1/common
cp mercs.rom /media/$USER/POCKET/Assets/jtcps1/common
cp mercsj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp mercsu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp mercsur1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp msword.rom /media/$USER/POCKET/Assets/jtcps1/common
cp mswordj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp mswordr1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp mswordu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp mtwins.rom /media/$USER/POCKET/Assets/jtcps1/common
cp nemo.rom /media/$USER/POCKET/Assets/jtcps1/common
cp nemoj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp nemor1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp pang3.rom /media/$USER/POCKET/Assets/jtcps1/common
cp pang3b.rom /media/$USER/POCKET/Assets/jtcps1/common
cp pang3b2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp pang3b3.rom /media/$USER/POCKET/Assets/jtcps1/common
cp pang3j.rom /media/$USER/POCKET/Assets/jtcps1/common
cp pang3r1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp pnickj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp pokonyan.rom /media/$USER/POCKET/Assets/jtcps1/common
cp qad.rom /media/$USER/POCKET/Assets/jtcps1/common
cp qadjr.rom /media/$USER/POCKET/Assets/jtcps1/common
cp qtono2j.rom /media/$USER/POCKET/Assets/jtcps1/common
cp rockmanj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2acc.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2acca.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2accp2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2amf.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2amf2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2amf3.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2bhh.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ce.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ceblp.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2celtw.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ceds6.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ceea.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ceja.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2cejb.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2cejc.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ces6a.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ces6b.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ces6c.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2cet.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ceua.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ceub.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ceuc.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ceupl.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2dkot2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2dongb.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ea.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2eb.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ebbl.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ebbl2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ebbl3.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ed.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ee.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ef.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2em.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2en.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2hf.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2hfj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2hfu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2j.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2j17.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ja.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2jc.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2jf.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2jh.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2jl.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2koryu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2level.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2m10.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2m2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2m3.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2m4.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2m5.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2m6.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2m7.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2m8.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2qp1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2qp2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2rb.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2rb2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2rb3.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2re.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2red.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2redp2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2rk.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2rules.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2stt.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2thndr.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2thdr2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ua.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ub.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2uc.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ud.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ue.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2uf.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ug.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2uh.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2ui.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2uk.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2um.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2v004.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sf2yyc.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sfach.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sfzbch.rom /media/$USER/POCKET/Assets/jtcps1/common
cp sfzch.rom /media/$USER/POCKET/Assets/jtcps1/common
cp slammast.rom /media/$USER/POCKET/Assets/jtcps1/common
cp slammstu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp strider.rom /media/$USER/POCKET/Assets/jtcps1/common
cp striderj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp stridrjr.rom /media/$USER/POCKET/Assets/jtcps1/common
cp stridrua.rom /media/$USER/POCKET/Assets/jtcps1/common
cp stridruc.rom /media/$USER/POCKET/Assets/jtcps1/common
cp unsquad.rom /media/$USER/POCKET/Assets/jtcps1/common
cp varth.rom /media/$USER/POCKET/Assets/jtcps1/common
cp varthb2.rom /media/$USER/POCKET/Assets/jtcps1/common
cp varthj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp varthjr.rom /media/$USER/POCKET/Assets/jtcps1/common
cp varthr1.rom /media/$USER/POCKET/Assets/jtcps1/common
cp varthu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp willow.rom /media/$USER/POCKET/Assets/jtcps1/common
cp willowj.rom /media/$USER/POCKET/Assets/jtcps1/common
cp willowu.rom /media/$USER/POCKET/Assets/jtcps1/common
cp willowuo.rom /media/$USER/POCKET/Assets/jtcps1/common
cp wonder3.rom /media/$USER/POCKET/Assets/jtcps1/common
