#!/bin/bash

cp 1944.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 1944d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 1944j.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 19xx.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 19xxa.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 19xxar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 19xxb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 19xxd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 19xxh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 19xxj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 19xxjr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 19xxjr2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp 19xxu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp armwar.rom /media/$USER/POCKET/Assets/jtcps2/common
cp armwar1d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp armwara.rom /media/$USER/POCKET/Assets/jtcps2/common
cp armwaar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp armwarr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp armwaru.rom /media/$USER/POCKET/Assets/jtcps2/common
cp armwaru1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp avsp.rom /media/$USER/POCKET/Assets/jtcps2/common
cp avspa.rom /media/$USER/POCKET/Assets/jtcps2/common
cp avspd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp avsph.rom /media/$USER/POCKET/Assets/jtcps2/common
cp avspj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp avspu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp batcir.rom /media/$USER/POCKET/Assets/jtcps2/common
cp batcira.rom /media/$USER/POCKET/Assets/jtcps2/common
cp batcird.rom /media/$USER/POCKET/Assets/jtcps2/common
cp batcirj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp choko.rom /media/$USER/POCKET/Assets/jtcps2/common
cp csclub.rom /media/$USER/POCKET/Assets/jtcps2/common
cp csclub1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp csclub1d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp cscluba.rom /media/$USER/POCKET/Assets/jtcps2/common
cp csclubh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp csclubj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp csclubjy.rom /media/$USER/POCKET/Assets/jtcps2/common
cp cybots.rom /media/$USER/POCKET/Assets/jtcps2/common
cp cybotsj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp cybotsjd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp cybotsu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp cybotsud.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsom.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsoma.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomjr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomjr2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomr2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomr3.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomud.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddsomur1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtod.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtoda.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtodar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtodd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtodh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtodhr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtodhr2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtodj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtodjr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtodjr2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtodr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtodu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ddtodur1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp dimahoo.rom /media/$USER/POCKET/Assets/jtcps2/common
cp dimahoou.rom /media/$USER/POCKET/Assets/jtcps2/common
cp dimahoud.rom /media/$USER/POCKET/Assets/jtcps2/common
cp dstlk.rom /media/$USER/POCKET/Assets/jtcps2/common
cp dstlka.rom /media/$USER/POCKET/Assets/jtcps2/common
cp dstlkh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp dstlku.rom /media/$USER/POCKET/Assets/jtcps2/common
cp dstlku1d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp dstlkur1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ecofghtr.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ecofgtra.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ecofgtrd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ecofgtrh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ecofgtru.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ecofgru1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp gigawing.rom /media/$USER/POCKET/Assets/jtcps2/common
cp gigawnga.rom /media/$USER/POCKET/Assets/jtcps2/common
cp gigawngb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp gigawngd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp gigawngh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp gigawngj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp gigawgjd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp gmahou.rom /media/$USER/POCKET/Assets/jtcps2/common
cp hsf2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp hsf2a.rom /media/$USER/POCKET/Assets/jtcps2/common
cp hsf2d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp hsf2j.rom /media/$USER/POCKET/Assets/jtcps2/common
cp hsf2j1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp jyangoku.rom /media/$USER/POCKET/Assets/jtcps2/common
cp megaman2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp megamn2a.rom /media/$USER/POCKET/Assets/jtcps2/common
cp megamn2h.rom /media/$USER/POCKET/Assets/jtcps2/common
cp megamn2d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mmatrix.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mmatrixd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mmatrixj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mpang.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mpanga.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mpangj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mpangr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mpangu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp msh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp msha.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshbr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshjr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshud.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsf.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsfa.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsfa1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsfb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsfb1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsfh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsfj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsfj1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsfj2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsfu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsfu1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mshvsu1d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvsc.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvsca.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvscar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvscb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvsch.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvscj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvscjr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvscjing.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvscr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvscu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvscud.rom /media/$USER/POCKET/Assets/jtcps2/common
cp mvscur1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp nwarr.rom /media/$USER/POCKET/Assets/jtcps2/common
cp nwarra.rom /media/$USER/POCKET/Assets/jtcps2/common
cp nwarrb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp nwarrh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp nwarru.rom /media/$USER/POCKET/Assets/jtcps2/common
cp nwarrud.rom /media/$USER/POCKET/Assets/jtcps2/common
cp pfghtj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp pgear.rom /media/$USER/POCKET/Assets/jtcps2/common
cp pgearr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp progear.rom /media/$USER/POCKET/Assets/jtcps2/common
cp progeara.rom /media/$USER/POCKET/Assets/jtcps2/common
cp progearj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp progejbl.rom /media/$USER/POCKET/Assets/jtcps2/common
cp progerjd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp progerud.rom /media/$USER/POCKET/Assets/jtcps2/common
cp pzloop2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp pzloop2j.rom /media/$USER/POCKET/Assets/jtcps2/common
cp pzloo2jd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp pzloojr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp qndream.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ringdest.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ringdsta.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ringdstb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ringdsth.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ringdstd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp rockmn2j.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa2u.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa2ur1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa3.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa3b.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa3h.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa3hr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa3u.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa3ud.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa3ur1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfa3us.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfad.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfar2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfar3.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfau.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2a.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2ad.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2al.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2alb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2ald.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2alh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2alj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2b.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2br1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2h.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2j.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2jd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2jr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz2n.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz3a.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz3ar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz3j.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz3jr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz3jr2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfz3jr2d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfza.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfzar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfzb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfzbr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfzh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfzhr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfzj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfzjr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sfzjr2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sgemf.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sgemfa.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sgemfd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp sgemfh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp smbomb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp smbombr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp spf2t.rom /media/$USER/POCKET/Assets/jtcps2/common
cp spf2ta.rom /media/$USER/POCKET/Assets/jtcps2/common
cp spf2td.rom /media/$USER/POCKET/Assets/jtcps2/common
cp spf2th.rom /media/$USER/POCKET/Assets/jtcps2/common
cp spf2tu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp spf2xj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp spf2xjd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2a.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2ar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2h.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2j.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2jr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2jr2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2r1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2t.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2ta.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2tad.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2tb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2tba.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2tbd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2tbh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2tbj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2tbj1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2tbr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2tbu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2th.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2tu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2tur1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2u.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2ud.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2xj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2xjr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2xr1d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp ssf2xr1r.rom /media/$USER/POCKET/Assets/jtcps2/common
cp uecology.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vampj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vampja.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vampjr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vhunt2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vhunt2d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vhunt2r1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vhuntj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vhuntjr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vhuntr1s.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vhuntjr2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vsav.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vsav2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vsav2d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vsava.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vsavb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vsavd.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vsavh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vsavj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp vsavu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcota.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotaa.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotar2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotab.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotah.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcothr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotaj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotaj1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotaj2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotaj3.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotajr.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotr1d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmcotau.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsf.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfa.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfar1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfar2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfar3.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfb.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfh.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfj.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfjr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfjr2.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfjr3.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfr1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfu.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfu1d.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfur1.rom /media/$USER/POCKET/Assets/jtcps2/common
cp xmvsfur2.rom /media/$USER/POCKET/Assets/jtcps2/common
