set_global_assignment -name VERILOG_MACRO "MISTTOP=jtcps1_mist"
set_global_assignment -name VERILOG_MACRO "SCAN2X_TYPE=2"
set_global_assignment -name VERILOG_MACRO "MISTER_VIDEO_MIXER=1"
set_global_assignment -name VERILOG_MACRO "NOCREDITS=1"
set_global_assignment -name VERILOG_MACRO "JTFRAME_OSD_NOCREDITS=1"
set_global_assignment -name VERILOG_MACRO "JTFRAME_MIST_DIPBASE=8"
